CREATE DATABASE Prueba01;

USE Prueba01;

CREATE TABLE Personas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    edad INT NOT NULL

);

SELECT * FROM Personas;